version: '3'

services:
  backend:
    build: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"

  vehicle_api:
    build: ./vehicle_api
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      - SECRET_KEY='thisismynewversionscreatversion'
      - USER='cdb'
      - PASSWORD='cdb123456'

  my-react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
      - vehicle_api
    volumes:
      - ./client/ngnix.conf:/etc/nginx/conf.d/default.conf

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - my-react-app
    ports:
      - "80:80"
